services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - TZ=Asis/Seoul
    volumes:
      - $HOME/docker/adguard/adguardhome/work:/opt/adguardhome/work
      - $HOME/docker/adguard/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - 3000:3000/tcp
      - 3000:3000/udp
      - 3001:3001/tcp
      - 3001:3001/udp
      - 443:443/tcp
      - 443:443/udp
      - 53:53/tcp
      - 53:53/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
      - 67:67/udp
#      - 68:68/udp
      - 784:784/udp
      - 80:80/tcp
      - 853:853/tcp
      - 853:853/udp
      - 8853:8853/udp
    restart: unless-stopped
